[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pet_dat_dog = "HDxktbmAF1fhPud3mdJ2k2ftZbwc4geX7pf5FfHGnVTe"

[registry]
# url = "http://localhost:8899"
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
prime = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pet-dat-dog.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pet-dat-dog.ts"
pet = "npx ts-mocha -p tsconfig.json -t 1000000 tests/pet.ts"
query = "npx ts-mocha -p tsconfig.json -t 1000000 tests/query.ts"
bonk = "npx ts-mocha -p tsconfig.json -t 1000000 tests/bonk.ts"
p2 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/player2.ts"
p3 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/p3.ts"
gm = "npx ts-mocha -p tsconfig.json -t 1000000 tests/global_max_mainnet.ts"
ms1 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/multisig_init_global.ts"
ms2 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/multisig_init_Maximilian.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"