[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pet_that_dog = "3HTdwKWxXccHzh88pyAADqCpaxYpYpuE7vdPkmMReH7M"

[programs.localnet]
pet_that_dog = "3HTdwKWxXccHzh88pyAADqCpaxYpYpuE7vdPkmMReH7M"

[programs.mainnet]
pet_that_dog = "3HTdwKWxXccHzh88pyAADqCpaxYpYpuE7vdPkmMReH7M"

[registry]
# url = "http://localhost:8899"
# url = "https://api.mainnet-beta.solana.com"
url = "https://api.devnet.solana.com"

[provider]
# cluster = "mainnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
bonk = "npx ts-mocha -p tsconfig.json -t 1000000 tests/bonk.ts"
gm = "npx ts-mocha -p tsconfig.json -t 1000000 tests/global_max_mainnet.ts"
init_mainnet = "npx ts-mocha -p tsconfig.json -t 1000000 tests/init_mainnet.ts"
max_mainnet = "npx ts-mocha -p tsconfig.json -t 1000000 tests/multisig_init_max_mainnet.ts"
p2 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/player2.ts"
p3 = "npx ts-mocha -p tsconfig.json -t 1000000 tests/p3.ts"
pet = "npx ts-mocha -p tsconfig.json -t 1000000 tests/pet.ts"
prime = "npx ts-mocha -p tsconfig.json -t 1000000 tests/pet-that-dog.ts"
query = "npx ts-mocha -p tsconfig.json -t 1000000 tests/query.ts"
test = "NODE_OPTIONS='--no-deprecation' npx ts-mocha -p tsconfig.json -t 1000000 tests/pet-that-dog.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"
