[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
pet_dat_dog = "DNHVjKARnjUuTykjqhbrQ1veV8YFkmqiwP65EKd19YPT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"