[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pet_dat_dog = "4Z2Tjaw2a4tMUnefnPExQ7sE4UfYSZhZT1pMDKfvAofL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
prime = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pet-dat-dog.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
pet = "npx ts-mocha -p tsconfig.json -t 1000000 tests/pet.ts"
query = "npx ts-mocha -p tsconfig.json -t 1000000 tests/query_program.ts"